// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH;

#nullable disable

namespace QLBH.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20231104132546_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1L,
                            BirthDay = new DateTime(2000, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "012345678901",
                            Email = "NguyenVanT@gmail.com",
                            Gender = false,
                            Name = "Nguyễn Văn Thơ",
                            Phone = "0757294361"
                        },
                        new
                        {
                            CustomerID = 2L,
                            BirthDay = new DateTime(1999, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "068903241849",
                            Email = "THNT56565@email.com",
                            Gender = true,
                            Name = "Trần Thị Hồng Ngọc",
                            Phone = "0989102574"
                        },
                        new
                        {
                            CustomerID = 3L,
                            BirthDay = new DateTime(1987, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "054321319302",
                            Email = "LeQuocSong@gmail.com",
                            Gender = true,
                            Name = "Lê Quốc Ca",
                            Phone = "0343671829"
                        },
                        new
                        {
                            CustomerID = 4L,
                            BirthDay = new DateTime(2001, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "097654810294",
                            Email = "PhamAnhCope@email.com",
                            Gender = true,
                            Name = "Phạm Anh Đồng",
                            Phone = "0460492715"
                        },
                        new
                        {
                            CustomerID = 5L,
                            BirthDay = new DateTime(1995, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "024683719492",
                            Email = "HoangHiBird@gmail.com",
                            Gender = true,
                            Name = "Hoàng Thị Én",
                            Phone = "0431568942"
                        },
                        new
                        {
                            CustomerID = 6L,
                            BirthDay = new DateTime(1996, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "015793819201",
                            Email = "VuMinhFea@email.com",
                            Gender = false,
                            Name = "Vũ Minh Phương",
                            Phone = "0520873456"
                        },
                        new
                        {
                            CustomerID = 7L,
                            BirthDay = new DateTime(1998, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "086420728192",
                            Email = "GiangBui@email.com",
                            Name = "Bùi Văn Giang",
                            Phone = "0678941320"
                        },
                        new
                        {
                            CustomerID = 8L,
                            BirthDay = new DateTime(1999, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "075314839292",
                            Email = "NgoThank@gmail.com",
                            Gender = false,
                            Name = "Ngô Thanh Huyền",
                            Phone = "0412456789"
                        },
                        new
                        {
                            CustomerID = 9L,
                            BirthDay = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "062082738592",
                            Email = "ThuThao123@email.com",
                            Gender = true,
                            Name = "Đặng Thu Thảo",
                            Phone = "0793502748"
                        },
                        new
                        {
                            CustomerID = 10L,
                            BirthDay = new DateTime(1993, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "031425928473",
                            Email = "TamTu@gmail.com",
                            Gender = true,
                            Name = "Trương Tâm Tú",
                            Phone = "0736251849"
                        },
                        new
                        {
                            CustomerID = 11L,
                            BirthDay = new DateTime(1992, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "076542819382",
                            Email = "HaiQuan@gmail.com",
                            Gender = true,
                            Name = "Lâm Quang Khải",
                            Phone = "0750781693"
                        },
                        new
                        {
                            CustomerID = 12L,
                            BirthDay = new DateTime(1997, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "020987371284",
                            Email = "LaiHo@email.com",
                            Gender = true,
                            Name = "Hồ Thị Lai",
                            Phone = "0568923147"
                        },
                        new
                        {
                            CustomerID = 13L,
                            BirthDay = new DateTime(1978, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "057898392012",
                            Email = "HoangMink@email.com",
                            Gender = false,
                            Name = "Đỗ Hoàng Minh",
                            Phone = "0424589310"
                        },
                        new
                        {
                            CustomerID = 14L,
                            BirthDay = new DateTime(2003, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "013404859402",
                            Email = "ChildNkee@gmail.com",
                            Gender = false,
                            Name = "Châu Minh Nhi",
                            Phone = "0371820394"
                        },
                        new
                        {
                            CustomerID = 15L,
                            BirthDay = new DateTime(2002, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "045672817492",
                            Email = "MaiTki@email.com",
                            Gender = true,
                            Name = "Mai Thị Oanh",
                            Phone = "0296047258"
                        },
                        new
                        {
                            CustomerID = 16L,
                            BirthDay = new DateTime(2000, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "09760385748",
                            Email = "PinkHappy@gmail.com",
                            Gender = false,
                            Name = "Nguyễn Hồng Phúc",
                            Phone = "0512345678"
                        },
                        new
                        {
                            CustomerID = 17L,
                            BirthDay = new DateTime(1984, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "05310758492",
                            Email = "LTTQuỳnh@email.com",
                            Gender = true,
                            Name = "Lê Thị thanh Quỳnh",
                            Phone = "0787463291"
                        },
                        new
                        {
                            CustomerID = 18L,
                            BirthDay = new DateTime(1980, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "068904657322",
                            Email = "ThanhPhanTea @gmail.com",
                            Gender = true,
                            Name = "Phan Thanh Trà",
                            Phone = "0953127964"
                        },
                        new
                        {
                            CustomerID = 19L,
                            BirthDay = new DateTime(1988, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "034567271392",
                            Email = "TranSVan@gmail.com",
                            Gender = true,
                            Name = "Trần Văn Sĩ",
                            Phone = "0974920518"
                        },
                        new
                        {
                            CustomerID = 20L,
                            BirthDay = new DateTime(1993, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CCCD = "080121839201",
                            Email = "ILoveHN@gmail.com",
                            Gender = true,
                            Name = "Đinh Quốc Tuân",
                            Phone = "0938562914"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
